export const CardListData = [
  {
    id: 1,
    elem: 'img',
    src: '/static/6_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 2,
    elem: 'img',
    src: '/static/6_chervi.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 3,
    elem: 'img',
    src: '/static/6_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 4,
    elem: 'img',
    src: '/static/6_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 5,
    elem: 'img',
    src: '/static/7_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 6,
    elem: 'img',
    src: '/static/8_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 7,
    elem: 'img',
    src: '/static/8_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 8,
    elem: 'img',
    src: '/static/8_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 9,
    elem: 'img',
    src: '/static/9_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 10,
    elem: 'img',
    src: '/static/9_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 11,
    elem: 'img',
    src: '/static/10_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 12,
    elem: 'img',
    src: '/static/10_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 13,
    elem: 'img',
    src: '/static/A_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 14,
    elem: 'img',
    src: '/static/A_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 15,
    elem: 'img',
    src: '/static/A_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 16,
    elem: 'img',
    src: '/static/J_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 17,
    elem: 'img',
    src: '/static/K_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 18,
    elem: 'img',
    src: '/static/K_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 19,
    elem: 'img',
    src: '/static/K_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 20,
    elem: 'img',
    src: '/static/K_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 21,
    elem: 'img',
    src: '/static/7_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 22,
    elem: 'img',
    src: '/static/7_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 23,
    elem: 'img',
    src: '/static/7_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 24,
    elem: 'img',
    src: '/static/8_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 25,
    elem: 'img',
    src: '/static/9_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 26,
    elem: 'img',
    src: '/static/10_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 27,
    elem: 'img',
    src: '/static/10_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 28,
    elem: 'img',
    src: '/static/A_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 29,
    elem: 'img',
    src: '/static/J_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 30,
    elem: 'img',
    src: '/static/J_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 31,
    elem: 'img',
    src: '/static/J_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 32,
    elem: 'img',
    src: '/static/Q_chervy.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 33,
    elem: 'img',
    src: '/static/Q_bubny.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 34,
    elem: 'img',
    src: '/static/Q_kresty.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 35,
    elem: 'img',
    src: '/static/Q_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
  {
    id: 36,
    elem: 'img',
    src: '/static/9_piki.png',
    cardShirt: '/static/shirt.png',
    class: 'img_cart',
  },
];
