export const CardListData = [
  {
    id: 1,
    elem: 'img',
    src: './img/6_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 2,
    elem: 'img',
    src: './img/6_chervi.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 3,
    elem: 'img',
    src: './img/6_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 4,
    elem: 'img',
    src: './img/6_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 5,
    elem: 'img',
    src: './img/7_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 6,
    elem: 'img',
    src: './img/8_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 7,
    elem: 'img',
    src: './img/8_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 8,
    elem: 'img',
    src: './img/8_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 9,
    elem: 'img',
    src: './img/9_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 10,
    elem: 'img',
    src: './img/9_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 11,
    elem: 'img',
    src: './img/10_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 12,
    elem: 'img',
    src: './img/10_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 13,
    elem: 'img',
    src: './img/A_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 14,
    elem: 'img',
    src: './img/A_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 15,
    elem: 'img',
    src: './img/A_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 16,
    elem: 'img',
    src: './img/J_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 17,
    elem: 'img',
    src: './img/K_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 18,
    elem: 'img',
    src: './img/K_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 19,
    elem: 'img',
    src: './img/K_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 20,
    elem: 'img',
    src: './img/K_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 21,
    elem: 'img',
    src: './img/7_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 22,
    elem: 'img',
    src: './img/7_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 23,
    elem: 'img',
    src: './img/7_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 24,
    elem: 'img',
    src: './img/8_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 25,
    elem: 'img',
    src: './img/9_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 26,
    elem: 'img',
    src: './img/10_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 27,
    elem: 'img',
    src: './img/10_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 28,
    elem: 'img',
    src: './img/A_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 29,
    elem: 'img',
    src: './img/J_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 30,
    elem: 'img',
    src: './img/J_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 31,
    elem: 'img',
    src: './img/J_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 32,
    elem: 'img',
    src: './img/Q_chervy.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 33,
    elem: 'img',
    src: './img/Q_bubny.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 34,
    elem: 'img',
    src: './img/Q_kresty.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 35,
    elem: 'img',
    src: './img/Q_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
  {
    id: 36,
    elem: 'img',
    src: './img/9_piki.png',
    cardShirt: './img/shirt.png',
    class: 'img_cart',
  },
];
